[package]
name = "rust-rest-api-with-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
jsonwebtoken = "7.2"
serde = "1.0.188"
chrono = "0.4.26"
