[package]
name = "rust-rest-api-with-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5"
rocket_codegen = "0.5"
rocket_contrib = "0.5"
dotenv = "0.15"
bcrypt = "0.10"
jsonwebtoken = "7.2"
